### ISSUE TITLE
`to run in browser` message is wrong.

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-test-intern#50] opened 2017-07-11 15:07 UTC
**Bug** 

The `to run in browser` message needs to be changed to point at the `intern-local.js` config file.

**Comment by kitsonk** [comment] 2017-07-28 12:38
The whole alignment needs a bit of a refactor, let's address this under the broader issue.

Duplicate of #21

**Closed by kitsonk** 2017-07-28 12:38 UTC
